name: test-wolfram-activation

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [master]

jobs:
  test-wolfram:
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    env:
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Test Wolfram Engine
        run: |
          wolframscript -code "Print[\"Test: \" <> ToString[2 + 2]]"
          wolframscript -code "Print[\"System: \" <> $SystemID]" 

      - name: Build
        run: ./build.wls
